apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: bluelockrepo.azurecr.io/service-product:v2
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
